### PR TITLE
Gemify theme so it can be used as a gem-based theme

### PR DESCRIPTION
**Pull request by hungryzi**
Thank you for the theme! I wanted to use it as a gem-based theme so I prepare for that process in this PR. The commit messages explain the steps I took. Let me know what you think.

### CODE REVIEW

**Review by rhl-bthr — CHANGES_REQUESTED** [review]
Thanks for the pull request.
I don't agree with the concept of demo. All the files except the `posts` and their assets should be a part of the theme when anyone wants to use/extend it.

**Comment by hungryzi** [comment]
> I don't agree with the concept of demo. All the files except the posts and their assets should be a part of the theme when anyone wants to use/extend it.

The following files are only used in posts and pages. In other words, if one installs this theme, these files are not being used at all (`404.html` and `about.html` are not copied to `_sites` when a theme is installed). Thus, I think it makes sense to move them out of `assets`:

- `autumn.jpg`
- `monkey-typewriter.jpg`
- `404.jpg`
- `profile.png`

The only exception is `favicon.ico` so I've moved that back to `assets`. Let me know if that makes sense.

**Comment by rhl-bthr** [comment]
`404.html` gets rendered when someone tries to access a bad URL. Its absence would redirect to a GitHub page. This would be a feature regression in the gem-based theme.
`about.html` is called from config.yml and is rendered in the navbar. Its absence would leave the theme broken when viewed without any changes.

Even otherwise, I've given this some more thought - I don't think gemifying the theme adds a lot of value. The theme is rather easy to use and extend directly from forking this repository

Thanks for the effort.

**Comment by hungryzi** [comment]
As a user, I prefer adding a theme as a gem, and modify only files I need to modify, instead of pulling in every single file into my repo. Incidentally, I've gone with another theme so I don't need this to be merged. I respect your decision and thank you for having a look.

**Pull request closed without merging**
